<?php

class ETC_CmsCtf7_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_ctf7';
    protected $title = 'CMS Contact Form 7';
    protected $icon = 'eicon-form-horizontal';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/soapee\/wp-content\/themes\/soapee\/elementor\/templates\/widgets\/cms_ctf7\/layout\/layout1.png"},"2":{"label":"Layout 2","image":"http:\/\/localhost\/soapee\/wp-content\/themes\/soapee\/elementor\/templates\/widgets\/cms_ctf7\/layout\/layout2.png"},"3":{"label":"Layout 3","image":"http:\/\/localhost\/soapee\/wp-content\/themes\/soapee\/elementor\/templates\/widgets\/cms_ctf7\/layout\/layout3.png"},"4":{"label":"Layout 4","image":"http:\/\/localhost\/soapee\/wp-content\/themes\/soapee\/elementor\/templates\/widgets\/cms_ctf7\/layout\/layout4.png"}},"prefix_class":"cms-cf7-layout-"}]},{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"form_title","label":"Form Title","type":"text","default":"","placeholder":"Enter Form title","label_block":true},{"name":"form_desc","label":"Form Description","type":"textarea","default":"","placeholder":"Enter your text","label_block":true},{"name":"ctf7_id","label":"Select Form","type":"select","options":{"1071":"Free Call Back 02","538":"Ask Us","502":"Drop Us A Line","337":"Get a Free Consultation","5":"Contact form 1"}}]},{"name":"image_section","label":"Banner Settings","tab":"content","controls":[{"name":"form_banner","label":"Choose your banner","type":"media","label_block":true,"condition":{"layout":["1","2"]}},{"name":"thumbnail_size","type":"image-size","control_type":"group","default":"full","condition":{"form_banner!":""}}],"condition":{"layout":["1","2"]}},{"name":"icon_section","label":"Icon Settings","tab":"content","controls":[{"name":"selected_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"far fa-paper-plane","library":"fa-regular"}},{"name":"icon_size","type":"slider","range":{"px":{"min":20,"max":200}},"size_units":["px"],"default":{"unit":"px","size":50}}],"condition":{"layout":["2","4"]}}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}