<?php

class ETC_CmsProcess_Widget extends Elementor_Theme_Core_Widget_Base{
    protected $name = 'cms_process';
    protected $title = 'CMS Process';
    protected $icon = 'eicon-counter';
    protected $categories = array( 'elementor-theme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"text-align","label":"Content Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Left","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"Right","icon":"eicon-text-align-right"},"justify":{"title":"Justified","icon":"eicon-text-align-justify"}},"default":"center"},{"name":"col_sm","label":"Columns SM Devices","type":"select","default":"1","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"col_md","label":"Columns MD Devices","type":"select","default":"2","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"col_lg","label":"Columns LG Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"col_xl","label":"Columns XL Devices","type":"select","default":"4","options":{"1":"1","2":"2","3":"3","4":"4","6":"6","12":"12"}},{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"https:\/\/demo.cmssuperheroes.com\/themeforest\/soapee\/wp-content\/themes\/soapee\/elementor\/templates\/widgets\/cms_process\/layout\/layout1.png"}},"prefix_class":"cms-process-layout-"}]},{"name":"section_process","label":"Process","tab":"content","controls":[{"name":"process","label":"Add your process","type":"repeater","default":[{"process_name":"Online Scheduling","process_icon":[],"process_desc":"Book & pay online. We\u2019ll match you with a trusted, experienced house cleaner"},{"process_name":"Clean Carefully","process_icon":[],"process_desc":"Every cleaner is friendly and reliable. They\u2019ve been background-checked & rated 5-stars"},{"process_name":"Enjoy Cleanliness","process_icon":[],"process_desc":"Now, enjoy the cleanliness of your beloved home, if there are errors we guarantee 100%"}],"controls":[{"name":"process_icon","label":"Icon","type":"icons","fa4compatibility":"icon","default":{"value":"fas fa-star","library":"fa-solid"}},{"name":"process_name","label":"Process Name","type":"text","label_block":true,"default":""},{"name":"process_desc","label":"Process Description","type":"text","label_block":true,"default":""}],"title_field":"{{{ process_name }}}"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}